from . import flight_base
from . import flight_flight
from . import flight_aerodrome
from . import flight_aircraft
from . import res_partner
from . import flight_pilottime
from . import flight_pilot_activity
from . import flight_event_time
from . import flight_crew
